# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-19 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170819_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='empty title', max_length=200, null=True),
        ),
    ]
